name: Git annotated tags experiments

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - runs: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = github.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'v1.0.1',
              message: 'hi',
              object: context.sha,
              type: 'commit',
            });
            console.log(`tagResponse: ${tagResponse}`);
            console.log(`tagResponse.data.sha: ${tagResponse.data.sha}`);
      - runs: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = github.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'v1.0.1',
              message: 'hi',
              object: context.sha,
              type: 'commit',
            });
            console.log(`tagResponse: ${tagResponse}`);
            console.log(`tagResponse.data.sha: ${tagResponse.data.sha}`);
            const refResponse = github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v1.0.1',
              sha: context.sha,
            });
      - runs: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = github.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'v1.0.2',
              message: 'hi2',
              object: context.sha,
              type: 'commit',
            });
            console.log(`tagResponse: ${tagResponse}`);
            console.log(`tagResponse.data.sha: ${tagResponse.data.sha}`);
            const refResponse = github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v1.0.2',
              sha: tagResponse.data.sha,
            });
      - runs: git tag
