name: Git annotated tags experiments

on:
  workflow_dispatch:
    inputs:
      tag1:
        type: string
        required: true
      tag2:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: git tag
      - run: git fetch --all --tags
      - run: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ inputs.tag1 }}',
              message: 'hi',
              object: context.sha,
              type: 'commit',
            });
            console.log('tagResponse:'); console.log(tagResponse);
      - run: git tag
      - run: git fetch --all --tags
      - run: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ inputs.tag1 }}',
              message: 'hi',
              object: context.sha,
              type: 'commit',
            });
            console.log('tagResponse:'); console.log(tagResponse);
            try {
              const refResponse = await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ inputs.tag1 }}',
                sha: context.sha,
              });
              console.log('refResponse:'); console.log(refResponse);
            } catch(err) {
              console.log("ref already exists");
            };
      - run: git tag
      - run: git fetch --all --tags
      - run: git tag
      - uses: actions/github-script@main
        with:
          script: |
            const tagResponse = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ inputs.tag2 }}',
              message: 'hi2',
              object: context.sha,
              type: 'commit',
            });
            console.log('tagResponse:'); console.log(tagResponse);
            console.log(`tagResponse.data.sha: ${tagResponse.data.sha}`);
            try {
              const refResponse = await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ inputs.tag2 }}',
                sha: tagResponse.data.sha,
              });
              console.log('refResponse:'); console.log(refResponse);
            } catch(err) {
              console.log("ref already exists");
            };
      - run: git tag
      - run: git fetch --all --tags
      - run: git tag
