name: CI - Testing Cache Anything New [in docker container]
on:
  workflow_dispatch:

jobs:
  testing_actions:
    name: Testing Actions | Job
    runs-on: 'ubuntu-latest'
    container: 
      image: 'ubuntu:16.04'
      options: --user 0
    steps:
      - uses: actions/checkout@v3
      
      - run: ls -A

      # It is required to execute the cache action.
      #   id: It will be use in the cache anything action.
      #   path: It always should be start with 'runner.temp'.
      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/cache-directory-example
          key: cache-hello-world-key-docker-v1.20
          
      # Implement the cache anything action.
      #   is_cached: Use the previous cache action id.
      #   cache: It should be the same as the cache 'path'. The default prefix is '${{ runner.temp }}/' for this reason
      #          it's not required in this field.
      - name: Step -> Cache anything
        uses: plu5/cache-anything-new-in-container-action@main
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-directory-example
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'

      - name: Step -> Use the cache
        run: |
          find /home/ -iname hello.txt 2> /dev/null || true
          whereis pandoc || true
