name: Commit message manipulation

on:
  workflow_dispatch:
  push:
    paths: ['edit-this-to-trigger-push-workflows']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          echo "Full message:"
          echo "$MESSAGE"
          ECHOEDMESSAGE=$(echo -e "$MESSAGE")
          echo "echo -e message:"
          echo "$ECHOEDMESSAGE"
          TRUNCATEDMESSAGE=$(tail -n +3 "$ECHOEDMESSAGE")
          echo "Truncated message:"
          echo "$TRUNCATEDMESSAGE"
