name: Commit message manipulation

on:
  workflow_dispatch:
  push:
    paths: ['edit-this-to-trigger-push-workflows']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "Full message:\n${{ github.event.head_commit.message }}"
          TRUNCATED_MESSAGE=$(tail -n +3 "${{ github.event.head_commit.message }}")
          echo -e "Truncated message:\n$TRUNCATED_MESSAGE"
