name: Commit message manipulation

on:
  workflow_dispatch:
  push:
    paths: ['edit-this-to-trigger-push-workflows']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.head_commit.message }}" > commit_msg
          echo "Full message: $(cat commit_msg)"
          echo "Truncated message: $(tail -n +3 commit_msg)"
