name: Container with image ubuntu:16.04 check version of glibc

on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest  # 1
    container:
      image: ubuntu:16.04   # 2
      options: --user 0     # 3
    steps:
      - name: Check version
        run: |
          grep VERSION= /etc/os-release  # -> VERSION="16.04.7 LTS (Xenial Xerus)"
          ldd --version                  # -> ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
