name: Can you use container on Windows runner?

on:
  workflow_dispatch:

jobs:
  linux:
    name: Windows
    runs-on: windows-latest
    container:
      image: ubuntu:16.04
      options: --user 0
    steps:
      - name: Check version
        run: |
          grep VERSION= /etc/os-release
          ldd --version
