name: Container with image ubuntu:16.04 check version of gcc

on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
      options: --user 0
    steps:
      - name: Check version
        run: |
          grep VERSION= /etc/os-release
          ldd -v
