name: docker pull and run

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Run image & check version
        run: |
          CMDS="grep VERSION= /etc/os-release
                ldd --version"
          docker run --entrypoint=bash ubuntu:16.04 -c "${CMDS//$'\n'/;}"
