name: docker pull and run

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 1

      - name: Run image & check version
        run: |                     # 2-6:
          CMDS="grep VERSION= /etc/os-release
                ldd --version"

          docker run \
            -v ${{ github.workspace }}:/usr/src/app \
            --entrypoint=sh \
            ubuntu:16.04 \
            -c "${CMDS//$'\n'/;}"
