name: Exclude matrix

on:
  workflow_dispatch:
    inputs:
      some_bool:
        type: boolean
        required: false
        default: true

jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      some_bool: ${{ steps.a.outputs.some_bool }}
    steps:
      - id: a
        name: get inputs
        run: |
          SOME_BOOL=true
          if [ -n "${{ inputs.some_bool }}" ]; then
            SOME_BOOL=${{ inputs.some_bool }}
          fi
          echo "some_bool=$SOME_BOOL" >> $GITHUB_OUTPUT

  build:
    needs: data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_linux:
          - ${{ needs.data.outputs.some_bool }}
        exclude:
          - os: ubuntu-latest
            build_linux: 'false'
    steps:
      - run: echo ${{ matrix.os }}
