name: Exclude matrix

on:
  workflow_dispatch:
    inputs:
      some_bool:
        type: boolean
        required: false
        default: true

jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      some_bool: ${{ steps.a.outputs.some_bool }}
    steps:
      - id: a
        name: get inputs
        run: echo "some_bool=true" >> $GITHUB_OUTPUT

  build:
    needs: data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/orgs/community/discussions/26253
        build_linux:
          - ${{ needs.data.outputs.some_bool }}
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
        exclude:
          - os: ubuntu-latest
            build_linux: 'false'
    steps:
      - run: echo ${{ matrix.os }}
