name: Exclude matrix

on:
  workflow_dispatch:
    inputs:
      build_linux:
        type: boolean
        required: false
        default: true
      build_windows:
        type: boolean
        required: false
        default: true

jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      some_bool: ${{ steps.a.outputs.some_bool }}
    steps:
      - id: a
        name: get inputs
        run: |
          BUILD_LINUX=true; BUILD_WINDOWS=true
          if [ -n "${{ inputs.build_linux }}" ]; then
            BUILD_LINUX=${{ inputs.build_linux }}; BUILD_WINDOWS=${{ inputs.build_windows }}
          fi
          echo -e "build_linux=$BUILD_LINUX\nbuild_windows=$BUILD_WINDOWS" >> $GITHUB_OUTPUT

  build:
    needs: data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_linux:
          - ${{ needs.data.outputs.build-linux }}
        build_windows:
          - ${{ needs.data.outputs.build-windows }}
        exclude:
          - os: ubuntu-latest
            build_linux: 'false'
          - os: windows-latest
            build_windows: 'false'
    steps:
      - run: echo ${{ matrix.os }}
