name: Exclude matrix

on:
  workflow_dispatch:
    inputs:
      build_linux:
        type: boolean
        required: false
        default: true
      build_windows:
        type: boolean
        required: false
        default: true
      
jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.a.outputs.os }}
    steps:
      - id: a
        name: get inputs
        run: |
          arr=()
          if [ -n "${{ inputs.build_linux }}" ]; then
            [ ${{ inputs.build_linux }} = 'true' ] && arr+=('ubuntu-latest')
            [ ${{ inputs.build_windows }} = 'true' ] && arr+=('windows-latest')
          else
            arr=('ubuntu-latest' 'windows-latest')
          fi
          s=$(printf ",\"%s\"" "${arr[@]}")
          echo os=[${s:1}] >> $GITHUB_OUTPUT

  build:
    needs: data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(needs.data.outputs.os) }}
    steps:
      - run: echo ${{ matrix.os }}
